# Generated by Django 4.1.1 on 2022-10-12 12:54

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название теста')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Тест активен')),
                ('out_url_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тестер. Метод АПИ')),
                ('out_request_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='Тестер. Метод')),
                ('out_request_body', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Тестер. Тело запроса')),
                ('out_response_code', models.IntegerField(blank=True, null=True, verbose_name='Тестер. Ожидаемый код ответа')),
                ('out_response_body', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Тестер. Тело ответа')),
                ('in_url_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглушка. Метод АПИ')),
                ('in_request_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='Заглушка. Метод')),
                ('in_request_body', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Заглушка. Тело запроса')),
                ('in_response_code', models.IntegerField(blank=True, null=True, verbose_name='Заглушка. Код ответа')),
                ('in_response_body', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Заглушка. Тело ответа')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название проекта')),
                ('host', models.CharField(blank=True, max_length=255, null=True, verbose_name='Хост тестируемого приложения')),
                ('prefix', models.CharField(blank=True, max_length=255, null=True, verbose_name='Префикс пути')),
                ('base_headers', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Тестер. Базовые заголовки')),
                ('variables', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Переменные')),
                ('out_request_modifiers', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Тестер. Модификаторы запроса ')),
                ('out_response_modifiers', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Тестер. Модификаторы ответа ')),
                ('in_request_modifiers', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Заглушка. Модификаторы запроса ')),
                ('in_response_modifiers', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Заглушка. Модификаторы ответа ')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.project'),
        ),
    ]
